spring:
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 5000
  mail:
    # 配置 SMTP 服务器地址
    host: smtp.qq.com
    # 发送者邮箱
    username: 228292390@qq.com
    # 配置密码，注意不是真正的密码，而是刚刚申请到的授权码
    password: bdzvndhbbxtwbigc
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
    port: 587
    properties:
      mail:
        smtp:
          ssl:
            enable: false
server:
  port: 10086
